name: Terraform Destroy for dev workflows
on:
  pull_request:
    types: [closed]
    branches:
      - main
env:
  TF_DIR: ./terraform

jobs:
  terraform-plan:
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials(OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::980069008226:role/github_actions_OIDC_role
          aws-region: us-east-1
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set TF_VAR_env
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "TF_VAR_env=${{ vars.env }}" >> $GITHUB_ENV
          else
            echo "TF_VAR_env=$BRANCH_NAME" >> $GITHUB_ENV
          fi
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          BRANCH_NAME: ${{ github.head_ref }}

      - name: environment variable
        run: echo "Environment is $TF_VAR_env"
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform apply
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TF_DIR }}
