name: Terraform plan & apply for dev workflows
on:
  pull_request:
    branches: [main]
  # push:
  #   branches: [main]
env:
  TF_DIR: ./terraform

jobs:
  terraform-plan:
    environment: dev
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials(OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::980069008226:role/github_actions_OIDC_role
          aws-region: us-east-1
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set TF_VAR_env
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "push" && "$GITHUB_REF" == "refs/heads/main" ]]; then
            echo "TF_VAR_env=${{ vars.env }}" >> $GITHUB_ENV
          else
            echo "echo ${{ vars.env }}"

            echo "echo ${{ github.head_ref }}"
            echo "$GITHUB_EVENT_NAME"
            echo "$GITHUB_REF"
            echo "$GITHUB_REF_NAME"
            echo "TF_VAR_env=$BRANCH_NAME" >> $GITHUB_ENV
          fi
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_REF: ${{ github.ref }}
          BRANCH_NAME: ${{ github.head_ref }}
          # DEPLOY_ENVIRONMENT: ${{ job.env }}

      - name: environment variable
        run: echo "Environment is $TF_VAR_env"
      - name: Terraform init
        run: terraform init
        working-directory: ${{ env.TF_DIR }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt -t python

      - name: Create layer.zip
        run: |
          zip -r ${{ env.TF_DIR }}/layer.zip python/
          rm -rf python

      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TF_DIR }}

      - name: Terraform apply
        run: terraform apply tfplan
        working-directory: ${{ env.TF_DIR }}
