name: Terraform plan
on: 
  push:
    branches:  [main]


jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials(OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: <AWS_role>
          aws-region: us-east-1
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        uses: terraform init

      - name: Terraform plan
        uses: terraform plan -out=tfplan

      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
  terraform-applpy:
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials(OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: <AWS_role>
          aws-region: us-east-1
      
      - name: setup terraform
        uses: hashicorp/setup-terraform@v2

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .

      - name: Terraform init
        uses: terraform init

      - name: Terraform apply
        uses: terraform apply -auto-approve tfplan